name: Go

on:
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Test
        run: go test -v .

      - name: Configure git
        run: |
          git config --global user.name 'gptjddldi'
          git config --global user.email 'hystom38@gmail.com'

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout master branch
        run: git checkout master

      - name: Merge PR branch
        run: git merge origin/${{ github.event.pull_request.head.ref }}

      - name: Push changes
        run: git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
