name: Go Test and Merge

on:
  push:
    branches: [ "dev" ]

jobs:
  test-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Test
        run: go test -v .

      - name: Merge to master
        if: success()
        run: |
          git config --global user.name 'gptjddldi'
          git config --global user.email 'hystom38@gmail.com'
          git checkout master
          git merge --no-ff origin/dev -m "Merge dev into master"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}